version: "3.1"


services:
  app:
    build: .
    container_name: dukaan-backend
    environment:
      PORT: "${PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
    depends_on:
      - db 
    ports:
      - "3000:3000"

    command: npm run dev

    volumes:
      - .:/app/
      - /app/node_modules


  db:
    container_name: postgresdb
    image: postgres
    restart: always
    privileged: true
    environment:
      - POSTGRES_USER=shubham
      - POSTGRES_PASSWORD=jarvis
      - POSTGRES_DB=dukaan
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    ports:
      - 5432:5432


volumes:
  postgres_data: