version: "3.1"


services:
  app:
    build: .
    container_name: dukaan-backend
    environment:
      PORT: "${PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
    depends_on:
      - db 
    ports:
      - "3000:3000"

    command: npm run dev